server:
  port: 3003
spring:
  application:
    name:
      parking-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: /** URL DO SEU BANCO DE DADOS **/
    username: /** USER DO SEU BANCO DE DADOS **/
    password: /** SENHA DO SEU BANCO DE DADOS **/
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false